//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Db
{
    using System;
    using System.Collections.Generic;
    using Server.Db.Models;
    public partial class Coordinates : BaseDb
    {
    	public override long Id { get; set; }
    	public decimal Latitude { get; set; }
    	public decimal Longtitude { get; set; }
    	public long UserId { get; set; }
    	public System.DateTime Date { get; set; }
    
    	public virtual User User { get; set; }
    }
}
