//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Db
{
    using System;
    using System.Collections.Generic;
    using Server.Db.Models;
    public partial class User : BaseDb
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	public User()
    	{
    		this.Coordinates = new HashSet<Coordinates>();
    	}
    
    	public override long Id { get; set; }
    	public System.Guid Password { get; set; }
    	public int Name { get; set; }
    
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	public virtual ICollection<Coordinates> Coordinates { get; set; }
    }
}
